name: Deploy to EKS

on:
    workflow_dispatch:
    push:
      paths:
        - 'manifest/**'
      branches:
        - main
    pull_request:
      paths:
        - 'manifest/**'
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name softdesign-eks-cluster

      - name: Generate Kubernetes manifest with secrets
        run: |
          envsubst < ./manifest/db-secrets.yml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./manifest/*.yml
